
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

load_module /etc/nginx/modules/ngx_http_modsecurity_module.so;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        #listen 80 default_server;
        #listen [::]:80 default_server;

        server_name _;

        listen [::]:443 ssl;
        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/tc-crd.incku.com.tw/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tc-crd.incku.com.tw/privkey.pem;

        ssl_protocols TLSv1.2;

        client_max_body_size 10M;

        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsecurity/modsecurity_includes.conf;

        location / {
                proxy_pass https://nginx:443;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
            listen [::]:80;
            listen 80;

            client_max_body_size 1024M;
            server_name _;

            ##For Certbot SSL acme-challenge
            ##Docker service nginx use staticfloat/nginx-certbot as image
            ##The script in container /scripts/run_certbot.sh use 1337 for certbot --http-01-port
            location ~ /.well-known/acme-challenge/ {
                allow all;
                proxy_pass http://nginx:1337;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            ## redirect http to https www
            location / {
                return 301 https://tc-crd.incku.com.tw$request_uri;
            }
    }
}
